name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress

      - name: Run PHP CS Fixer Src (dry-run)
        run: vendor/bin/php-cs-fixer fix src --dry-run --diff
        
      - name: Run PHP CS Fixer Tests (dry-run)
        run: vendor/bin/php-cs-fixer fix tests --dry-run --diff

      - name: Run PHPUnit
        run: vendor/bin/phpunit --testdox
